server:
  port: 7576

spring:
  application:
    name: dyeingpie-backend
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    redis:
      database: 0           # Redis数据库索引
      host: 127.0.0.1        # 换成你的Redis的IP地址，在同一docker网络下，填写容器名即可
      port: 6379
      password:   # 换成你的Redis密码
      timeout: 5000ms   # 连接超时时间
      lettuce:
        pool:
          max-active: 20    # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
          max-wait: 5000ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dyeingpie?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai # 换成你的数据库IP地址，在同一docker网络下，填写容器名即可
    username: root
    password: **secret**
    druid:
      # 配置druid连接池
      initial-size: 5 # 初始化数量
      min-idle: 5     # 最小连接数
      max-active: 20  # 最大连接数
      max-wait: 60000 # 获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true # 是否缓存preparedStatement
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      filter:
        config:
          enabled: false
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
  mail:
    host: smtp.office365.com      #填写SMTP服务器的主机名
    username: --secret--   # 填写你邮箱
    password: --secret--                 # 填写你邮箱密码
    default-encoding: UTF-8
    port: 587                     # 填写SMTP服务器的主机的端口
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1       # 逻辑已删除
      logic-not-delete-value: 0   # 逻辑未删除

sa-token:
  token-name: Authentication           # token名称
  timeout: 2592000            # token有效期，单位s 默认30天, -1代表永不过期
  activity-timeout: 86400     # token临时有效期 (指定时间内无操作就视为token过期) 单位- 秒
  is-concurrent: true         # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-share: true              # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  isReadBody: false           # 是否尝试从 请求体 里读取 Token
  isReadHeader: true          # 是否尝试从 header 里读取 Token
  isReadCookie: true         # 是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie
  isPrint: false              # 是否在初始化配置时打印版本字符画
  is-log: false               # 是否输出操作日志
  token-style: random-64

management:
  endpoints:
    web:
      exposure:
        include: '*'