version: "3.8"

networks:
  tiedyer_net:

services:
  tiedyer-backend:
    build:
      context: ./dockerfiles/tiedyer
    image: tiedyer/backend:1.0
    container_name: tiedyer-backend
    restart: always
    ports:
      - "${EXPOSE_PORT}:${EXPOSE_PORT}"
    networks:
      - tiedyer_net
    environment:
      - EXPOSE_PORT
      - JWT_SECRET
      - APP_ID
      - APP_SECRET
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - REDIS_PASSWORD
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    volumes:
      - ${PROJECT_LOCATION}/tiedyer/resource:/root/resource
    depends_on:
      - rabbitmq
      - mysql
      - redis


  # MySQL
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - tiedyer_net
    environment:
      - MYSQL_ROOT_PASSWORD   # MySQL密码
      - MYSQL_DATABASE        # 新增数据库
      - TZ=Asia/Shanghai
    volumes:
      - ${PROJECT_LOCATION}/mysql/data:/var/lib/mysql
      - ${PROJECT_LOCATION}/mysql/conf/my.cnf:/etc/my.cnf
      - ${PROJECT_LOCATION}/mysql/init/:/docker-entrypoint-initdb.d/ # 数据库初始化脚本目录，当Mysql容器首次启动时将执行此目录下的所有SQL脚本

  # Redis
  redis:
    image: redis:6.2.6
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - tiedyer_net
    volumes:
      - ${PROJECT_LOCATION}/redis/redis.conf:/etc/redis/redis.conf
      - ${PROJECT_LOCATION}/redis/data:/data
    command: redis-server /etc/redis/redis.conf

  rabbitmq:
    # 使用安装有rabbitmq_delayed_message_exchange插件的RabbitMQ
    build:
      context: ./dockerfiles/rabbitmq
    image: tiedyer/rabbit:1.0
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - tiedyer_net
    environment:
      - RABBITMQ_DEFAULT_USER #  用户名
      - RABBITMQ_DEFAULT_PASS #  密码


  nginx:
    image: nginx:1.18.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tiedyer_net
    volumes:
      - ${PROJECT_LOCATION}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PROJECT_LOCATION}/nginx/html:/usr/share/nginx/html
